from google.adk.agents import Agent
from google.adk.tools import FunctionTool
from .tools import load_keywords, fetch_register_news, fetch_sans_isc_notes, write_report

root_agent = Agent(
    name="infosec_news_agent",
    model="gemini-2.5-flash",
    description="Curates infosec news from The Register and SANS ISC, then writes a digest report.",
    instruction="""You are an infosec news curator. Follow these steps every time you are run:

1. Call load_keywords to get the configured interest keywords.
2. Call fetch_register_news to get the latest stories from The Register.
3. Call fetch_sans_isc_notes to get the latest SANS Internet Storm Center podcast episodes.
4. Filter The Register stories: keep only those whose title or summary contains at least one keyword (case-insensitive).
5. Compose a markdown report with this structure:

---
# Infosec Digest — <today's date>

## Executive Summary
<3-5 bullet points hitting the most significant themes and stories across both sources>

---

## The Register — Keyword-Matched Stories
(<X> of <total> stories matched)

For each matched story:
**[Title](link)**
*Published: <date>*
<One-sentence summary>

---

## SANS ISC — Latest Podcast Notes
For each of the most recent episodes:
**[Title](link)**
*Published: <date>*
<2-3 sentence summary of the episode content>

---
*Generated by infosec_news_agent*
---

6. Call write_report with the completed markdown content.
7. Tell the user the report has been written and show the file path.""",
    tools=[
        FunctionTool(load_keywords),
        FunctionTool(fetch_register_news),
        FunctionTool(fetch_sans_isc_notes),
        FunctionTool(write_report),
    ],
)
