import re
import yaml
import feedparser
from datetime import datetime
from pathlib import Path
from google.adk.agents import Agent
from google.adk.tools import FunctionTool

_CONFIG_PATH = Path(__file__).parent.parent / "config" / "keywords.yaml"
_OUTPUT_DIR = Path(__file__).parent.parent / "output"
_REGISTER_FEED = "https://www.theregister.com/headlines.atom"
_SANS_ISC_FEED = "https://isc.sans.edu/podcast.rss"


def load_keywords() -> dict:
    """Load the list of keywords used to filter news stories from the config file."""
    with open(_CONFIG_PATH) as f:
        data = yaml.safe_load(f)
    keywords = data.get("keywords", [])
    return {"keywords": keywords, "count": len(keywords)}


def fetch_register_news() -> dict:
    """Fetch the latest news stories from The Register's Atom feed.

    Returns a list of stories with title, summary, link, and published date.
    """
    feed = feedparser.parse(_REGISTER_FEED)
    if feed.bozo and not feed.entries:
        return {"error": f"Failed to fetch feed: {feed.bozo_exception}", "stories": []}

    stories = [
        {
            "title": entry.get("title", ""),
            "summary": entry.get("summary", ""),
            "link": entry.get("link", ""),
            "published": entry.get("published", ""),
        }
        for entry in feed.entries
    ]
    return {"stories": stories, "total": len(stories)}


def fetch_sans_isc_notes() -> dict:
    """Fetch the latest episode notes from the SANS Internet Storm Center podcast RSS feed.

    Returns the most recent episodes with title, summary, link, and published date.
    """
    feed = feedparser.parse(_SANS_ISC_FEED)
    if feed.bozo and not feed.entries:
        return {"error": f"Failed to fetch feed: {feed.bozo_exception}", "episodes": []}

    episodes = []
    for entry in feed.entries[:10]:
        summary = entry.get("summary", "")
        # Strip HTML tags from the summary
        summary = re.sub(r"<[^>]+>", " ", summary).strip()
        summary = re.sub(r"\s+", " ", summary)
        episodes.append({
            "title": entry.get("title", ""),
            "summary": summary,
            "link": entry.get("link", ""),
            "published": entry.get("published", ""),
        })
    return {"episodes": episodes, "total": len(episodes)}


def write_report(content: str) -> dict:
    """Write the final digest report to a markdown file in the output directory.

    Args:
        content: The full markdown content of the report to write.

    Returns a dict with the path of the written file.
    """
    _OUTPUT_DIR.mkdir(exist_ok=True)
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"{date_str}_infosec_digest.md"
    output_path = _OUTPUT_DIR / filename
    output_path.write_text(content, encoding="utf-8")
    return {"path": str(output_path), "filename": filename}


root_agent = Agent(
    name="infosec_news_agent",
    model="gemini-2.5-flash",
    description="Curates infosec news from The Register and SANS ISC, then writes a digest report.",
    instruction="""You are an infosec news curator. Follow these steps every time you are run:

1. Call load_keywords to get the configured interest keywords.
2. Call fetch_register_news to get the latest stories from The Register.
3. Call fetch_sans_isc_notes to get the latest SANS Internet Storm Center podcast episodes.
4. Filter The Register stories: keep only those whose title or summary contains at least one keyword (case-insensitive).
5. Compose a markdown report with this structure:

---
# Infosec Digest — <today's date>

## Executive Summary
<3-5 bullet points hitting the most significant themes and stories across both sources>

---

## The Register — Keyword-Matched Stories
(<X> of <total> stories matched)

For each matched story:
**[Title](link)**
*Published: <date>*
<One-sentence summary>

---

## SANS ISC — Latest Podcast Notes
For each of the most recent episodes:
**[Title](link)**
*Published: <date>*
<2-3 sentence summary of the episode content>

---
*Generated by infosec_news_agent*
---

6. Call write_report with the completed markdown content.
7. Tell the user the report has been written and show the file path.""",
    tools=[
        FunctionTool(load_keywords),
        FunctionTool(fetch_register_news),
        FunctionTool(fetch_sans_isc_notes),
        FunctionTool(write_report),
    ],
)
