from google.adk.agents import Agent
from google.adk.tools import FunctionTool, load_memory
from .tools import load_keywords, fetch_register_news, fetch_sans_isc_notes, write_report
from .model_armor import before_model_callback, after_model_callback

root_agent = Agent(
    name="infosec_news_agent",
    model="gemini-2.5-flash",
    description="Curates infosec news from The Register and SANS ISC, then writes a digest report.",
    instruction="""You are an infosec news curator. Follow these steps every time you are run:

1. Call load_memory to recall any stories or topics you have already covered in previous runs, so you can avoid repeating them.
2. Call load_keywords to get the configured interest keywords.
3. Call fetch_register_news to get the latest stories from The Register.
4. Call fetch_sans_isc_notes to get the latest SANS Internet Storm Center podcast episodes.
5. Filter The Register stories: keep only those whose title or summary contains at least one keyword (case-insensitive). Skip any stories that match what you recalled from memory as already covered.
6. Compose a markdown report with this structure:

---
# Infosec Digest — <today's date>

## Executive Summary
<3-5 bullet points hitting the most significant themes and stories across both sources>

---

## The Register — Keyword-Matched Stories
(<X> of <total> stories matched)

For each matched story:
**[Title](link)**
*Published: <date>*
<One-sentence summary>

---

## SANS ISC — Latest Podcast Notes
For each of the most recent episodes:
**[Title](link)**
*Published: <date>*
<2-3 sentence summary of the episode content>

---
*Generated by infosec_news_agent*
---

7. Call write_report with the completed markdown content.
8. Tell the user the report has been written and show the file path.""",
    tools=[
        load_memory,
        FunctionTool(load_keywords),
        FunctionTool(fetch_register_news),
        FunctionTool(fetch_sans_isc_notes),
        FunctionTool(write_report),
    ],
    before_model_callback=before_model_callback,
    after_model_callback=after_model_callback,
)
